name: aoun_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  animations: ^2.0.11
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  flag: ^7.0.0
  fluentui_system_icons: ^1.1.265
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_card_swiper: ^7.0.2
  flutter_dotenv: ^5.2.1
  flutter_flip_card: ^0.0.6
  flutter_form_builder: ^10.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_pannable_rating_bar: ^2.7.2+1
  flutter_screenutil: ^5.9.3
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.0.17
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  location: ^8.0.0
  pinput: ^5.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_charts: ^28.2.12
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  webview_flutter: ^4.13.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/logo/LogoSplash.png
#   branding: assets/logo/LogoBranding.png
#   branding_bottom_padding: 24
#   color_dark: "#121212"
#   image_dark: assets/logo/LogoSplash.png
#   branding_dark: assets/logo/LogoBranding.png
#   android_12:
#     image: assets/logo/LogoSplash.png
#     icon_background_color: "#ffffff"
#     image_dark: assets/logo/LogoSplash.png
#     icon_background_color_dark: "#121212"
#   web: false
flutter:
  uses-material-design: true

  assets:
    - assets/image/introduction/
    - assets/image/logo/
    - assets/image/dialog/
    - assets/image/empty_image/
    - assets/image/
    - assets/icon/
    - assets/map_styles/
    - assets/image/map_maker/MyMakerLive.svg
    - assets/image/map_maker/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf

    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf

    - family: cairo
      fonts:
        - asset: assets/font/Cairo-Regular.ttf

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/image/
  output_path: lib/core/app_images/
  filename: app_images.dart
  field_prefix: null
